apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p3
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: GITLAB_URL
    targetRevision: master
    path: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  

