Vagrant.configure("2") do |config|

  # Server Worker
  config.vm.define "Master" do |master|

    master.vm.box = "generic/centos7"
    master.vm.hostname = "iltafahS"
    master.vm.network :private_network, ip: "192.168.56.110"
    master.vm.provision "shell", path: "scripts/k3sServerInstall.sh"  

    master.vm.synced_folder "./confs", "/var/www", create: true

    master.vm.provider "virtualbox" do |vb|
      vb.name = "iltafahS"
      vb.memory = "1024"
      vb.cpus = "2"
    end
  
  end

  # Client Worker
  config.vm.define "Slave" do |slave|

    slave.vm.box = "generic/centos7"
    slave.vm.hostname = "iltafahSW"
    slave.vm.network :private_network, ip: "192.168.56.111"
    slave.vm.provision "shell", path: "scripts/k3sAgentInstall.sh"  

    slave.vm.synced_folder "./confs", "/var/www", create: true

    slave.vm.provider "virtualbox" do |vb|
      vb.name = "iltafahSW"
      vb.memory = "1024"
      vb.cpus = "2"
    end
  
  end

end
