Vagrant.configure("2") do |config|
 
  config.vm.define "Master" do |master|
    master.vm.box = "generic/centos7"
    master.vm.hostname = "iltafahS"
    #master.vm.network "forwarded_port", guest: 6443, host: 6443
    master.vm.network :private_network, ip: "192.168.56.110"
    master.vm.provision "shell", path: "scripts/k3sInstall.sh"  
 

    #master.vm.synced_folder "./volume", "/var/www", create: true #, group: "www-data", owner: "www-data"
    master.vm.synced_folder "./ServerToken", "/var/www", create: true

    master.vm.provider "virtualbox" do |v|
      v.name = "iltafahS"
      v.memory = "1024"
      v.cpus = "2"
    end
  
  end
  
  config.vm.define "Slave" do |slave|
    slave.vm.box = "generic/centos7"
    slave.vm.hostname = "iltafahSW"
    slave.vm.network :private_network, ip: "192.168.56.111"
    slave.vm.provision "shell", path: "scripts/k3sSWInstall.sh"  
  
    #slave.vm.synced_folder "./volume", "/var/www", create: true #, group: "www-data", owner: "www-data"
    slave.vm.synced_folder "./ServerToken", "/var/www", create: true

    slave.vm.provider "virtualbox" do |v|
      v.name = "iltafahSW"
      v.memory = "1024"
      v.cpus = "2"
    end
  
  end


end


